version: '3.8'

services:
  pwtdev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: ["npm", "run", "dev", "--", "-p", "3000"]